#####################################################################################
# Build Step: build the python package
#####################################################################################
FROM python:3.12-slim AS builder
#
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*
#
RUN python -m pip install --upgrade pip build wheel
#
WORKDIR /tmp
COPY requirements/main.txt /tmp/requirements.txt
RUN pip install -r requirements.txt && \
    rm -rf /root/.cache/pip /tmp/requirements.txt
#
WORKDIR /tmp/package
# copy the package files
COPY . /tmp/package
#
RUN python -m build
#
#
#####################################################################################
# Final image
#####################################################################################
#
FROM python:3.12-slim
#
# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV DEBIAN_FRONTEND="noninteractive"
ENV DEBCONF_NONINTERACTIVE_SEEN=true
#
# install system dependencies
RUN apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends \
    tzdata \
    locales \
    bzip2 \
    ca-certificates \
    build-essential \
    wget \
    fonts-liberation \
    git \
    sudo \
    openssl \
    curl \
    tini \
    zip \
    unzip && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*
#
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8 \
    TZ=Etc/UTC
#
# I prefer colored prompt
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc
#
# create a non-root user
ARG GROUP_ID=1000
ENV GROUP_ID=${GROUP_ID}
RUN addgroup --system --gid ${GROUP_ID} user
ARG USER_ID=1000
ENV USER_ID=${USER_ID}
RUN adduser --disabled-password --gecos '' --shell /bin/bash --uid ${USER_ID} --gid ${GROUP_ID} user
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
RUN mkdir -p /home/user/tmp /home/user/.local/bin && \
    chown -R user:user /home/user
ENV PATH=/home/user/.local/bin:${PATH}
#
USER user
RUN pip install --upgrade pip
#
COPY --from=builder --chown=user:user /tmp/package/dist/*.whl /home/user/tmp/
RUN pip install --user /home/user/tmp/*.whl && \
    rm -rf /home/user/tmp
#
WORKDIR /home/user
#
ENV TINI_SUBREAPER=true
ENTRYPOINT ["/usr/bin/tini", "--"]
#
CMD ["my-package"]
#####################################################################################
# EOF
#####################################################################################
