
%%{init: {'sequence': {'actorSpacing': 10, 'width': 150}}}%%
sequenceDiagram
    participant assistant as Assistant
    participant user as User
    user->>assistant: Hello wa-1
    assistant->>user: I am an assistant.
