#####################################################################################
# Build Step: generate the static files.
#####################################################################################
FROM node:slim AS builder
#
RUN npm install --global bun
#
WORKDIR /app
#
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
#
COPY . .
RUN bun run build
#
#####################################################################################
# Final image
#####################################################################################
#
FROM node:slim
# a smiple static server
RUN npm install http-server -g
#
USER node
WORKDIR /home/node
COPY --from=builder --chown=node:node /app/dist /home/node/public
#
ARG PORT=3000
ENV PORT=${PORT}
#
EXPOSE ${PORT}
#
ENTRYPOINT ["http-server"]
#
CMD ["-a", "0.0.0.0", "--gzip"]
#####################################################################################
# EOF
#####################################################################################
