/**
 * SPDX-License-Identifier: Apache-2.0
 * Copyright 2024 - 2026 Waldiez & contributors
 */
export const ALLOWED_TAGS = [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "br",
    "hr",
    "strong",
    "em",
    "b",
    "i",
    "u",
    "s",
    "del",
    "mark",
    "a",
    "img",
    "ul",
    "ol",
    "li",
    "blockquote",
    "pre",
    "code",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "div",
    "span",
    "input",
];
export const ALLOWED_ATTR = [
    "href",
    "src",
    "alt",
    "title",
    "class",
    "id",
    "target",
    "rel",
    "type",
    "checked",
    "disabled",
    "align",
    "size",
    "width",
    "height",
    "colspan",
    "rowspan",
    "data-src",
];
export const ALLOWED_URI_REGEXP =
    // cspell: disable-next-line
    /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|data|waldiez):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;
